import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { AtlasTiles } from '../../../packages/core/src/world/atlas.ts'
import {
  AUTHORED_BLOCK_SPECS,
  AUTHORED_ITEM_SPECS,
  type AuthoredBlockSpec,
  type AuthoredItemSpec,
  DEFAULT_STARTER_INVENTORY_STACK_SPECS,
} from '../../../packages/core/src/world/content-spec.ts'
import { projectRoot } from './paths.ts'

const WORLD_ROOT = join(projectRoot, 'packages', 'core', 'src', 'world')
const GENERATED_ROOT = join(WORLD_ROOT, 'generated')
const ID_LOCK_PATH = join(WORLD_ROOT, 'content-id-lock.json')
const GENERATED_IDS_PATH = join(GENERATED_ROOT, 'content-ids.ts')
const GENERATED_REGISTRY_PATH = join(GENERATED_ROOT, 'content-registry.ts')

const BLOCK_ID_START = 1
const ITEM_ID_START = 101
const GENERATED_HEADER =
  '// This file is auto-generated by apps/cli/src/generate-content-registry.ts.\n// Do not edit by hand.\n\n'

interface ContentIdLock {
  blocks: Record<string, number>
  items: Record<string, number>
}

interface ResolvedBlockSpec extends AuthoredBlockSpec {
  id: number
}

interface ResolvedItemSpec extends AuthoredItemSpec {
  id: number
}

export interface GeneratedContentArtifacts {
  readonly lock: ContentIdLock
  readonly contentIdsSource: string
  readonly contentRegistrySource: string
}

const cloneLock = (lock: ContentIdLock): ContentIdLock => ({
  blocks: { ...lock.blocks },
  items: { ...lock.items },
})

const sortObjectEntries = (record: Record<string, number>): Array<[string, number]> =>
  Object.entries(record).sort(
    (left, right) => left[1] - right[1] || left[0].localeCompare(right[0]),
  )

const createMissingIdAllocator = (
  existingIds: readonly number[],
  startAt: number,
): (() => number) => {
  let nextId = Math.max(startAt - 1, ...existingIds) + 1
  return () => nextId++
}

const quote = (value: string): string => JSON.stringify(value)

const formatNumericIdMap = (name: string, entries: readonly [string, number][]): string => {
  const lines = entries.map(([key, value]) => `  ${key}: ${value},`)
  return `export const ${name} = {\n${lines.join('\n')}\n} as const;\n`
}

const formatIdValues = (
  name: string,
  sourceName: string,
  entries: readonly [string, number][],
): string => {
  const values = entries.map(([key]) => `${sourceName}.${key}`)
  return `export const ${name} = [${values.join(', ')}] as const;\n`
}

const formatBlockDefinition = (block: ResolvedBlockSpec): string => {
  const tiles = block.tiles
    ? `,\n    tiles: {\n      top: ${quote(block.tiles.top)},\n      bottom: ${quote(block.tiles.bottom)},\n      side: ${quote(block.tiles.side)},\n    }`
    : ''
  const renderPass = block.renderPass === null ? 'null' : quote(block.renderPass)
  const dropItemId = block.dropItemKey === null ? 'null' : `ITEM_IDS.${block.dropItemKey}`
  return `  [BLOCK_IDS.${block.key}]: {\n    id: BLOCK_IDS.${block.key},\n    name: ${quote(block.name)},\n    collidable: ${block.collidable},\n    breakable: ${block.breakable},\n    occlusion: ${quote(block.occlusion)},\n    renderPass: ${renderPass},\n    dropItemId: ${dropItemId},\n    emittedLightLevel: ${block.emittedLightLevel},\n    color: [${block.color.join(', ')}]${tiles},\n  },`
}

const formatItemDefinition = (item: ResolvedItemSpec): string => {
  const placesBlockId = item.placesBlockKey === null ? 'null' : `BLOCK_IDS.${item.placesBlockKey}`
  const renderBlockId = item.renderBlockKey === null ? 'null' : `BLOCK_IDS.${item.renderBlockKey}`
  return `  [ITEM_IDS.${item.key}]: {\n    id: ITEM_IDS.${item.key},\n    name: ${quote(item.name)},\n    color: [${item.color.join(', ')}],\n    maxStackSize: ${item.maxStackSize},\n    placesBlockId: ${placesBlockId},\n    renderBlockId: ${renderBlockId},\n  },`
}

const validateUniqueKeys = (
  blocks: readonly AuthoredBlockSpec[],
  items: readonly AuthoredItemSpec[],
): void => {
  const blockKeys = new Set<string>()
  for (const block of blocks) {
    if (blockKeys.has(block.key)) {
      throw new Error(`Duplicate block key "${block.key}" in content spec.`)
    }
    blockKeys.add(block.key)
  }

  const itemKeys = new Set<string>()
  for (const item of items) {
    if (itemKeys.has(item.key)) {
      throw new Error(`Duplicate item key "${item.key}" in content spec.`)
    }
    itemKeys.add(item.key)
  }
}

const validateReferences = (
  blocks: readonly AuthoredBlockSpec[],
  items: readonly AuthoredItemSpec[],
): void => {
  const blockKeys = new Set(blocks.map((block) => block.key))
  const itemKeys = new Set(items.map((item) => item.key))
  const atlasTileKeys = new Set(Object.keys(AtlasTiles))

  for (const block of blocks) {
    if (block.dropItemKey !== null && !itemKeys.has(block.dropItemKey)) {
      throw new Error(
        `Block "${block.key}" references unknown drop item key "${block.dropItemKey}".`,
      )
    }

    if (block.tiles) {
      for (const tile of Object.values(block.tiles)) {
        if (!atlasTileKeys.has(tile)) {
          throw new Error(`Block "${block.key}" references unknown atlas tile "${tile}".`)
        }
      }
    }
  }

  for (const item of items) {
    if (item.placesBlockKey !== null && !blockKeys.has(item.placesBlockKey)) {
      throw new Error(
        `Item "${item.key}" references unknown placeable block key "${item.placesBlockKey}".`,
      )
    }
    if (item.renderBlockKey !== null && !blockKeys.has(item.renderBlockKey)) {
      throw new Error(
        `Item "${item.key}" references unknown render block key "${item.renderBlockKey}".`,
      )
    }
  }

  const starterSlots = new Set<number>()
  for (const stack of DEFAULT_STARTER_INVENTORY_STACK_SPECS) {
    if (!itemKeys.has(stack.itemKey)) {
      throw new Error(`Starter inventory references unknown item key "${stack.itemKey}".`)
    }
    if (stack.slot < 0 || !Number.isInteger(stack.slot)) {
      throw new Error(`Starter inventory slot "${stack.slot}" must be a non-negative integer.`)
    }
    if (starterSlots.has(stack.slot)) {
      throw new Error(`Starter inventory defines duplicate slot "${stack.slot}".`)
    }
    starterSlots.add(stack.slot)
  }
}

const validateLock = (
  lock: ContentIdLock,
  blocks: readonly AuthoredBlockSpec[],
  items: readonly AuthoredItemSpec[],
): void => {
  const blockKeys = new Set(blocks.map((block) => block.key))
  const itemKeys = new Set(items.map((item) => item.key))

  for (const key of Object.keys(lock.blocks)) {
    if (!blockKeys.has(key)) {
      throw new Error(`Content id lock contains unknown block key "${key}".`)
    }
  }

  for (const key of Object.keys(lock.items)) {
    if (!itemKeys.has(key)) {
      throw new Error(`Content id lock contains unknown item key "${key}".`)
    }
  }
}

const assertUniqueIds = (label: string, entries: readonly [string, number][]): void => {
  const seen = new Map<number, string>()
  for (const [key, id] of entries) {
    const existing = seen.get(id)
    if (existing) {
      throw new Error(`Duplicate ${label} id ${id} for keys "${existing}" and "${key}".`)
    }
    seen.set(id, key)
  }
}

const resolveIds = (
  specs: readonly { key: string }[],
  lockedIds: Record<string, number>,
  startAt: number,
): Record<string, number> => {
  const resolved = { ...lockedIds }
  const allocateId = createMissingIdAllocator(Object.values(lockedIds), startAt)

  for (const spec of specs) {
    if (resolved[spec.key] === undefined) {
      resolved[spec.key] = allocateId()
    }
  }

  return resolved
}

const resolveBlockSpecs = (idsByKey: Record<string, number>): ResolvedBlockSpec[] =>
  AUTHORED_BLOCK_SPECS.map((block) => ({
    ...block,
    id: idsByKey[block.key]!,
  }))

const resolveItemSpecs = (idsByKey: Record<string, number>): ResolvedItemSpec[] =>
  AUTHORED_ITEM_SPECS.map((item) => ({
    ...item,
    id: idsByKey[item.key]!,
  }))

const formatLockJson = (lock: ContentIdLock): string =>
  `${JSON.stringify(
    {
      blocks: Object.fromEntries(sortObjectEntries(lock.blocks)),
      items: Object.fromEntries(sortObjectEntries(lock.items)),
    },
    null,
    2,
  )}\n`

const buildContentIdsSource = (
  blockEntries: readonly [string, number][],
  itemEntries: readonly [string, number][],
): string =>
  [
    GENERATED_HEADER,
    formatNumericIdMap('BLOCK_IDS', blockEntries),
    '\n',
    formatNumericIdMap('ITEM_IDS', itemEntries),
    '\n',
    'export type BlockKey = keyof typeof BLOCK_IDS;\n',
    'export type ItemKey = keyof typeof ITEM_IDS;\n',
    '\n',
    'export type BlockId = (typeof BLOCK_IDS)[BlockKey];\n',
    'export type ItemId = (typeof ITEM_IDS)[ItemKey];\n',
    '\n',
    formatIdValues('BLOCK_ID_VALUES', 'BLOCK_IDS', blockEntries),
    formatIdValues('ITEM_ID_VALUES', 'ITEM_IDS', itemEntries),
  ].join('')

const buildContentRegistrySource = (
  blocks: readonly ResolvedBlockSpec[],
  items: readonly ResolvedItemSpec[],
): string => {
  const blockDefinitions = blocks.map(formatBlockDefinition).join('\n')
  const itemDefinitions = items.map(formatItemDefinition).join('\n')
  const starterStacks = DEFAULT_STARTER_INVENTORY_STACK_SPECS.map(
    (stack) =>
      `  { slot: ${stack.slot}, itemId: ITEM_IDS.${stack.itemKey}, count: ${stack.count} },`,
  ).join('\n')

  return [
    GENERATED_HEADER,
    'import type { AtlasTileId } from "../atlas.ts";\n',
    'import { BLOCK_IDS, type BlockId, ITEM_IDS, type ItemId } from "./content-ids.ts";\n',
    '\n',
    'export interface GeneratedBlockTiles {\n',
    '  top: AtlasTileId;\n',
    '  bottom: AtlasTileId;\n',
    '  side: AtlasTileId;\n',
    '}\n',
    '\n',
    'export interface GeneratedBlockDefinition {\n',
    '  id: BlockId;\n',
    '  name: string;\n',
    '  collidable: boolean;\n',
    '  breakable: boolean;\n',
    '  occlusion: "none" | "full" | "self";\n',
    '  renderPass: "opaque" | "cutout" | "translucent" | null;\n',
    '  dropItemId: ItemId | null;\n',
    '  emittedLightLevel: number;\n',
    '  color: [number, number, number];\n',
    '  tiles?: GeneratedBlockTiles;\n',
    '}\n',
    '\n',
    'export interface GeneratedItemDefinition {\n',
    '  id: ItemId;\n',
    '  name: string;\n',
    '  color: [number, number, number];\n',
    '  maxStackSize: number;\n',
    '  placesBlockId: BlockId | null;\n',
    '  renderBlockId: BlockId | null;\n',
    '}\n',
    '\n',
    'export interface StarterInventoryStackDefinition {\n',
    '  slot: number;\n',
    '  itemId: ItemId;\n',
    '  count: number;\n',
    '}\n',
    '\n',
    'export const GENERATED_BLOCK_DEFINITIONS = {\n',
    `${blockDefinitions}\n`,
    '} as const satisfies Record<BlockId, GeneratedBlockDefinition>;\n',
    '\n',
    'export const GENERATED_ITEM_DEFINITIONS = {\n',
    `${itemDefinitions}\n`,
    '} as const satisfies Record<ItemId, GeneratedItemDefinition>;\n',
    '\n',
    'export const STARTER_INVENTORY_STACKS = [\n',
    `${starterStacks}\n`,
    '] as const satisfies readonly StarterInventoryStackDefinition[];\n',
  ].join('')
}

const readContentIdLock = async (): Promise<ContentIdLock> => {
  const lock = JSON.parse(await readFile(ID_LOCK_PATH, 'utf8')) as ContentIdLock
  if (
    typeof lock !== 'object' ||
    lock === null ||
    typeof lock.blocks !== 'object' ||
    lock.blocks === null ||
    typeof lock.items !== 'object' ||
    lock.items === null
  ) {
    throw new Error('Content id lock file is invalid.')
  }
  return cloneLock(lock)
}

export const buildGeneratedContentArtifacts = async (): Promise<GeneratedContentArtifacts> => {
  validateUniqueKeys(AUTHORED_BLOCK_SPECS, AUTHORED_ITEM_SPECS)
  validateReferences(AUTHORED_BLOCK_SPECS, AUTHORED_ITEM_SPECS)

  const lock = await readContentIdLock()
  validateLock(lock, AUTHORED_BLOCK_SPECS, AUTHORED_ITEM_SPECS)

  lock.blocks = resolveIds(AUTHORED_BLOCK_SPECS, lock.blocks, BLOCK_ID_START)
  lock.items = resolveIds(AUTHORED_ITEM_SPECS, lock.items, ITEM_ID_START)

  const blockEntries = sortObjectEntries(lock.blocks)
  const itemEntries = sortObjectEntries(lock.items)
  assertUniqueIds('block', blockEntries)
  assertUniqueIds('item', itemEntries)

  const resolvedBlocks = resolveBlockSpecs(lock.blocks)
  const resolvedItems = resolveItemSpecs(lock.items)

  return {
    lock,
    contentIdsSource: buildContentIdsSource(blockEntries, itemEntries),
    contentRegistrySource: buildContentRegistrySource(resolvedBlocks, resolvedItems),
  }
}

export const writeGeneratedContentArtifacts = async (
  artifacts: GeneratedContentArtifacts,
): Promise<void> => {
  await mkdir(GENERATED_ROOT, { recursive: true })
  await writeFile(ID_LOCK_PATH, formatLockJson(artifacts.lock), 'utf8')
  await writeFile(GENERATED_IDS_PATH, artifacts.contentIdsSource, 'utf8')
  await writeFile(GENERATED_REGISTRY_PATH, artifacts.contentRegistrySource, 'utf8')
}

export const syncGeneratedContentRegistry = async (): Promise<GeneratedContentArtifacts> => {
  const artifacts = await buildGeneratedContentArtifacts()
  await writeGeneratedContentArtifacts(artifacts)
  return artifacts
}
